server.port=9090

# Connexion PostgreSQL (Remplace 'medical_db' par ton nom de base)
spring.datasource.url=jdbc:postgresql://localhost:5432/rendez_vous
spring.datasource.username=myuser
spring.datasource.password=allerenavant2006

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
